### ISSUE TITLE
Gradient messages

### ISSUE THREAD

**Issue by TorrenStark** [MrUniverse44/PixelMOTD#2]
How do I create Gradient messages?

**Comment by MrUniverse44** [comment]
`<gradient: #hex-#hex:hey hello>` But currently we're investigating an issue with this variable, because colors aren't working correctly.

**Comment by MrUniverse44** [comment]
The new owner of PixelMOTD @sebastnchan is working to fix this issue, this github will no longer be the main of PixelMOTD, any information here: **https://github.com/sebastnchan/PixelMOTD** (New Discord)
